[pytest]

testpaths =
    tests

pythonpath =
    .

markers =
    integration: tests that require Kafka, Spark and PostgreSQL services

addopts = -ra

norecursedirs =
    .git
    .venv
    __pycache__
    .pytest_cache
    airflow/logs
    checkpoints
    logs